### ISSUE TITLE
check 0s problem

### ISSUE THREAD

**Issue by RPanczak** [RPanczak/ISPM_geo-mortality#17]
the finer the spatial resolution the bigger the problem of zero counts will be 
it might be prudent to check how bad it is prior to analyses
perhaps aggregation to higher level unit (than Gemeinde) will be needed?

**Comment by jriou** [comment]
Is this a problem because of the Poisson? Couldn't this be solved just with zero-inflated Poisson or negative binomial likelihood?

**Comment by gkonstantinoudis** [comment]
Re: Will solve #29 once I get up to date pops linked. One caveat there is they stratified on large regions. What would be our solution for that? Grossregionen? Arbeitsmarktgrossregionen?
The subdivided by regions since they are using very small areas and they had computational power issues. I dont expect computational issues with Gemeinde, but if we need to do smth about it and select smth similar, I would say cantons. 

Re: Bethan's work - that ignores time of the year completely right?
Correct they do ingore time entirely, as they did not have any strong hypotheses about spacetime covariates.
