### ISSUE TITLE
mid year populations

### ISSUE THREAD

**Issue by RPanczak** [RPanczak/ISPM_geo-mortality#34]
Hi both

Community level data with age breakdown as we need is (most likely) only available for 31st Dec 📆 each year.
And of course it's missing for 2021 with very slim chances of getting sth fresher. 
Is that a massive problem? Should we interpolate it to sth? mid year?

**Comment by jriou** [comment]
Ok you know better but I'm surprised population can be so impactful. Maybe because I underestimate the variation from year to year? I don't really see how a variation of <1% on the denominator can have so much impact? Is it because it's more than 1%?

Anyway your proposition with a linear model is much better regardless.

**Comment by jriou** [comment]
Ok thanks. About the meeting I'm happy to do it anytime!
